# Site settings
title: Taveon Nelson
email: taveonnelsonn@gmail.com
url: 
description: "Portfolio of a cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Fullstack Developer - SOC Analyst"
meta_author: Nelson Taveon
color:
  primary: 2dd7b9 #80B3FF
  primary-rgb: "45,215,185" #"128,179,255"
  secondary: 48597a #FD6E8A
  secondary-dark: 001846 #A2122F

# Footer settings
footer:
  copyright: Taveon Nelson
  location: Location
  social: Contact Me
  credits: Credits

social:
  - title: linkedin
    url: https://www.linkedin.com/in/taveon-nelson-968622293/
  - title: github
    url: https://github.com/457R0

email:
  email-url: mailto:taveonnelsonn@gmail.com

location:
  - line: Minnesota, USA

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
